version: "3"
services:
  backend:
    build: ./php
    image: backend_php:latest
    container_name: backend_container
    hostname: "backend"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on:
      - db_backend
  db_backend:
    image: postgres:13
    container_name: postgres_db
    restart: unless-stopped
    tty: true
    ports:
      - "15432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/conf.d/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: culture_monitoring
      TZ: Asia/Jakarta
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
  nginx_backend:
    build: ./nginx
    image: nginx_backend:latest
    container_name: nginx_container
    hostname: "nginx_backend"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
